### ISSUE TITLE
Wrap iterator

### ISSUE THREAD

**Issue by gkorepanov** [gkorepanov/CS-4sem#1]
[There](https://github.com/gkorepanov/CS-4sem/commit/866952b8753db04cafdd36b6531ee119dc27226c#diff-628bfe821edfe1964d1bced10b3f9877L68) is an explanation of why it is needed.

- [x] create branch
- [x] declare interface
- [x] implement interface
- [x] fix older functions using iterators (TODO's added)
- [x] compile and retest
- [x] merge

**Comment by uteshevia** [comment]
*Markdown failure*
TODO lists requires **one** symbol in the brackets, like `[x]` or `[ ]`, not `[  x  ]`.

**Comment by uteshevia** [comment]
*Feature request*
Can't iterate in reverse order. `rbegin` and `rend` required.

**Comment by uteshevia** [comment]
<b><I> *Feature request* </I></b>
Can't iterate in reverse order. `rbegin` and `rend` required.
Let's introduce iteration direction.
