### ISSUE TITLE
Change types names

### ISSUE THREAD

**Issue by gkorepanov** [gkorepanov/CS-4sem#2]
Names like type_t are reserved for POSIX and shouldn't be used. Thus our strcutures should be renamed with CamelCase convention.

**Comment by uteshevia** [comment]
Agreed.

**Comment by uteshevia** [comment]
`list_t` -> `List`
`list_node_t` -> `ListNode`
`list_iterator_t` -> `ListIterator`

**Comment by uteshevia** [comment]
**I've propagated these changes to `iterator_wrap` branch, be aware!**
